### ISSUE TITLE
cost怎么算的 没看出来。

### ISSUE THREAD

**Issue by Mioke** [ibireme/YYCache#13]
BenchMark里Value都是NSData：
`NSData *value = [NSData dataWithBytes:&i length:sizeof(int)];`

然后使用`[yy setObject:values[i] forKey:keys[i]];`，在setObject:forKey:里：
```objc
- (void)setObject:(id)object forKey:(id)key {
    [self setObject:object forKey:key withCost:0];
}
```
之后就没看见对cost的操作了。都是node直接复制`node->_cost = cost`。

所以不太清楚cost累加的。

我自己写的Cache里，是对`CFMutableDictionaryRef`转成`NSMutableDictionary`然后KeyedArchive得到NSData然后算data.length来判断size。

**Comment by ibireme** [comment]
这个 Cost 只是提供给使用者一个可选参数，使用者不用也完全没问题。这个可以看一下 NSCache 对于 cost 参数的注释：

The cost value is used to compute a sum encompassing the costs of all the objects in the cache. Typically, the obvious cost is the size of the value in bytes. If that information is not readily available, you should not go through the trouble of trying to compute it, as doing so will drive up the cost of using the cache. Pass in 0 for the cost value if you otherwise have nothing useful to pass, or simply use the setObject:forKey: method, which does not require a cost value to be passed in.

**Comment by Mioke** [comment]
那`根据设定缓存最大值，当超过最大值时自动清理`这个功能，一部分是需要使用者自己实现的是么？

**Comment by Mioke** [comment]
I understand. That's why `count` exists.
